FROM golang:1.19-alpine as builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /out/app ./cmd/worker

FROM alpine:latest
WORKDIR /worker
COPY --from=builder /out/app /worker/app
ENTRYPOINT ["/worker/app"]